version: '3.1'

services:
  postgres:
    image: postgres:14.1
    restart: no
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmanager
    ports:
      - "5432:5432"

  java_app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    depends_on:
      - postgres
    environment:
      - TZ=Europe/Warsaw
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8080:8080"
