version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
  taskmanager:
    container_name: taskmanager
    build: .
#    image: 086152582278.dkr.ecr.eu-north-1.amazonaws.com/taskmanager
    restart: always
    ports:
      - '8000:8000'
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_AUTH_SOURCE: ${DB_AUTH_SOURCE}